# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('lecture_no', models.IntegerField()),
                ('link', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
