# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('name', models.CharField(max_length=30, unique=True)),
                ('lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('slid_link', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
