# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('facutly', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_no',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course_id',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='classroom.course'),
        ),
    ]
