# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20171114_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='facutly',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='course_id',
            new_name='course',
        ),
    ]
