# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20171115_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='link',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
