# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20171205_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('total_score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='classroom.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='exam',
        ),
        migrations.AddField(
            model_name='grade',
            name='test',
            field=models.ForeignKey(default='-123', on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='classroom.test'),
        ),
    ]
