# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20171207_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
